name: Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-mend-scan:
    uses: Bella-yuuu/bella-mend/.github/workflows/template.yml@main
    with:
      PRODUCT_NAME: "Cindy_Github"
      PROJECT_NAME: "0805"
    secrets:
      MEND_USERKEY: ${{ secrets.MEND_USERKEY }}
