name: Scan Template

on:
  workflow_call:
    inputs:
      PRODUCT_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      MEND_USERKEY:
        required: true

jobs:
  scan:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: 設定環境變數並執行 Scan.bat
        shell: cmd
        run: |
          echo 設定變數...
          set PRODUCT_NAME=${{ inputs.PRODUCT_NAME }}
          set PROJECT_NAME=${{ inputs.PROJECT_NAME }}
          set USERKEY=${{ secrets.MEND_USERKEY }}

          echo 執行 Scan.bat...
          call "C:\WS-OnlineScan\Scan.bat"
