name: Scan Template

on:
  workflow_call:
    inputs:
      PRODUCT_NAME:
        required: true
        type: string
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      userKey:
        required: true

jobs:
  scan:
    runs-on: [self-hosted, windows] 
    env:
      USERKEY: ${{ secrets.MEND_USERKEY }}
    steps:
      - name: 設定環境變數
        run: |
          echo PRODUCT_NAME=${{ inputs.PRODUCT_NAME }}>> %GITHUB_ENV%
          echo PROJECT_NAME=${{ inputs.PROJECT_NAME }}>> %GITHUB_ENV%
        shell: cmd

      - name: 確認變數
        run: |
          echo PRODUCT_NAME=%PRODUCT_NAME%
          echo PROJECT_NAME=%PROJECT_NAME%
        shell: cmd

      - name: 執行掃描腳本
        run: |
          echo "執行掃描..."
          C:\WS-OnlineScan\Scan.bat
        shell: cmd
